image:
  name: golang:1.16-alpine3.14
  entrypoint: ["/bin/sh","-c"]
 
before_script:
  - go version

stages:
  - test
  - build
  - push

test:
  stage: test
  script: 
    - echo "test"

build:
  stage: build
  scrpit: 
    - echo "build"

push:
  stage: push
  script: 
    - echo "push"
